### PR TITLE
No need for render prop

### PR DESCRIPTION
**Pull request by rijk**
Thanks for the tutorial! Just FYI, when using Framer Motion you don't need a render prop/`static` for the `Menu.Items`, you can just let it manage its own state and motion’s `initial`/`animate` will take care of animation when headless-ui mounts the menu items.

### CODE REVIEW

**Comment by samselikoff** [comment]
Ughh - hate when I mess things like this up in videos!

I think the reason I had this is because originally I also had AnimatePresence and used an `exit` animation. In that case you would need `static` and the render prop, correct?

**Comment by rijk** [comment]
Hah, no worries, it still works! Just wanted to let you know. And no, even with AnimatePresence/`exit` you’d still not need a render prop; this will happen automatically as the component is unmounted by headless-ui. I think the reason you thought you needed it is headless-ui needs it [for their Transition implementation](https://github.com/tailwindlabs/headlessui/blob/develop/packages/%40headlessui-react/README.md#transitions) (which is different).

**Comment by rijk** [comment]
Actually, scratch that! I though it would work by wrapping `<Menu.Items>` in `<AnimatePresence>` but it actually doesn't, as the Menu.Items component is kept in the tree even when closed (not sure why):

image

So yes, in this case you would need a render prop 🙂

**Comment by samselikoff** [comment]
Interesting! Ok good to know though, if you just want animate in you don't need static.

I saw it from this guy: https://github.com/tailwindlabs/headlessui/blob/develop/packages/%40headlessui-react/pages/menu/menu-with-framer-motion.tsx

Thanks for chiming in, learned something new!

**Comment by rijk** [comment]
I did find an `unmount` parameter in the docs which I thought would solve this, but unfortunately it doesn't seem to do much. I submitted an issue for it: https://github.com/tailwindlabs/headlessui/issues/134

**Pull request closed without merging**
